Repository codehaus-plexus/plexus-pom, pull requests merged in 2023-05, with the labels that each got.

#162 Remove test-javadoc report and configuration improvements
  pom.xml
Labels: enhancement

#164 Drop no longer needed configuration for checkstyle plugin
  pom.xml
Labels: maintenance

#163 Add DependencyManagement for JUnit5
  pom.xml
Labels: dependencies

#165 Sync enforcer configuration setup with ASF
  pom.xml
Labels: maintenance

#167 Checkstyle license check - depend on file from released branch
  pom.xml
Labels: bug

#168 One time spotless apply
  pom.xml
Labels: maintenance

#170 javadoc notimestamp, to avoid noise in gh-pages
  pom.xml
Labels: enhancement
